#!/bin/bash

FROM_DATABASE=$1
TO_DATABASE=$2
FROM_VERSION=$3
# Pick any arguments after the required ones to pass them to the upgrade script
OTHER=${*:4}

if [[ -z "$FROM_DATABASE" || -z "$TO_DATABASE" || -z "$FROM_VERSION" ]]; then
    echo "Missing argument."
    echo "Syntax: $0 from_database to_database from_version"
    exit 1
fi

#invoke database.drop $TO_DATABASE
dropdb $TO_DATABASE
invoke database.copy $FROM_DATABASE $TO_DATABASE
export PYTHONPATH=trytond:proteus
./upgrades/upgrade $TO_DATABASE $FROM_VERSION $OTHER
